[package]
authors = ["The Rust Project Developers"]
name = "rustc_llvm"
version = "0.0.0"
build = "build.rs"

[lib]
name = "rustc_llvm"
path = "lib.rs"

[features]
static-libstdcpp = []
emscripten = []

[dependencies]
bitflags = "1.0"
libc = "0.2"
rustc_cratesio_shim = { path = "../librustc_cratesio_shim" }

[build-dependencies]
build_helper = { path = "../build_helper" }
cc = "1.0.1"
