[package]
authors = ["The Rust Project Developers"]
name = "rustc_traits"
version = "0.0.0"

[lib]
name = "rustc_traits"
path = "lib.rs"
crate-type = ["dylib"]

[dependencies]
bitflags = "1.0"
graphviz = { path = "../libgraphviz" }
log = { version = "0.4" }
rustc = { path = "../librustc" }
rustc_data_structures = { path = "../librustc_data_structures" }
syntax = { path = "../libsyntax" }
syntax_pos = { path = "../libsyntax_pos" }
chalk-engine = { version = "0.6.0", default-features=false }
