[package]
authors = ["The Rust Project Developers"]
name = "rustdoc"
version = "0.0.0"

[lib]
name = "rustdoc"
path = "lib.rs"

[dependencies]
pulldown-cmark = { version = "0.1.2", default-features = false }
tempdir = "0.3"
minifier = "0.0.11"
