[package]
authors = ["The Rust Project Developers"]
build = "build.rs"
name = "rustc_asan"
version = "0.0.0"

[lib]
name = "rustc_asan"
path = "lib.rs"
test = false

[build-dependencies]
build_helper = { path = "../build_helper" }
cmake = "0.1.18"

[dependencies]
alloc = { path = "../liballoc" }
alloc_system = { path = "../liballoc_system" }
core = { path = "../libcore" }
compiler_builtins = { path = "../rustc/compiler_builtins_shim" }
