[package]
authors = ["The Rust Project Developers"]
name = "test"
version = "0.0.0"

[lib]
name = "test"
path = "lib.rs"
crate-type = ["dylib", "rlib"]

[dependencies]
getopts = "0.2"
term = { path = "../libterm" }
