[package]
name = "rustc-std-workspace-core"
version = "1.0.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = 'MIT/Apache-2.0'
description = """
Hack for the compiler's own build system
"""

[lib]
path = "lib.rs"

[dependencies]
core = { path = "../../libcore" }
