[package]
authors = ["The Rust Project Developers"]
name = "rustc_resolve"
version = "0.0.0"

[lib]
name = "rustc_resolve"
path = "lib.rs"
crate-type = ["dylib"]
test = false

[dependencies]
log = "0.4"
syntax = { path = "../libsyntax" }
rustc = { path = "../librustc" }
arena = { path = "../libarena" }
rustc_errors = { path = "../librustc_errors" }
syntax_pos = { path = "../libsyntax_pos" }
rustc_data_structures = { path = "../librustc_data_structures" }
