[package]
name = "dlmalloc"
version = "0.0.0"
authors = ["The Rust Project Developers"]

[lib]
path = "../../dlmalloc/src/lib.rs"
test = false
bench = false
doc = false

[dependencies]
core = { path = "../../libcore" }
compiler_builtins = { path = "../../rustc/compiler_builtins_shim" }
