[package]
authors = ["The Rust Project Developers"]
name = "std_unicode"
version = "0.0.0"

[lib]
name = "std_unicode"
path = "lib.rs"
test = false
bench = false

[dependencies]
core = { path = "../libcore" }
compiler_builtins = { path = "../rustc/compiler_builtins_shim" }
