[package]
authors = ["The Rust Project Developers"]
name = "syntax"
version = "0.0.0"

[lib]
name = "syntax"
path = "lib.rs"
crate-type = ["dylib"]

[dependencies]
bitflags = "1.0"
serialize = { path = "../libserialize" }
log = "0.4"
scoped-tls = "0.1"
syntax_pos = { path = "../libsyntax_pos" }
rustc_errors = { path = "../librustc_errors" }
rustc_data_structures = { path = "../librustc_data_structures" }
rustc_target = { path = "../librustc_target" }
smallvec = { version = "0.6.7", features = ["union", "may_dangle"] }
