[package]
authors = ["The Rust Project Developers"]
name = "rustc_borrowck"
version = "0.0.0"

[lib]
name = "rustc_borrowck"
path = "lib.rs"
crate-type = ["dylib"]
test = false

[dependencies]
log = "0.4"
syntax = { path = "../libsyntax" }
syntax_pos = { path = "../libsyntax_pos" }
graphviz = { path = "../libgraphviz" }
rustc = { path = "../librustc" }
rustc_mir = { path = "../librustc_mir" }
rustc_errors = { path = "../librustc_errors" }
rustc_data_structures = { path = "../librustc_data_structures" }