[package]
authors = ["The Rust Project Developers"]
name = "rustc_target"
version = "0.0.0"

[lib]
name = "rustc_target"
path = "lib.rs"
crate-type = ["dylib"]

[dependencies]
bitflags = "1.0"
log = "0.4"
rustc_cratesio_shim = { path = "../librustc_cratesio_shim" }
serialize = { path = "../libserialize" }

[features]
jemalloc = []
