[package]
authors = ["The Rust Project Developers"]
name = "error_index_generator"
version = "0.0.0"

[dependencies]
rustdoc = { path = "../../librustdoc" }

[[bin]]
name = "error_index_generator"
path = "main.rs"
