[package]
authors = ["The Rust Project Developers"]
name = "rustc_typeck"
version = "0.0.0"

[lib]
name = "rustc_typeck"
path = "lib.rs"
crate-type = ["dylib"]
test = false

[dependencies]
log = "0.4"
syntax = { path = "../libsyntax" }
arena = { path = "../libarena" }
rustc = { path = "../librustc" }
rustc_data_structures = { path = "../librustc_data_structures" }
rustc_platform_intrinsics = { path = "../librustc_platform_intrinsics" }
rustc_target = { path = "../librustc_target" }
syntax_pos = { path = "../libsyntax_pos" }
rustc_errors = { path = "../librustc_errors" }
