[package]
authors = ["The Rust Project Developers"]
name = "alloc_jemalloc"
version = "0.0.0"
build = "build.rs"
links = "jemalloc"

[lib]
name = "alloc_jemalloc"
path = "lib.rs"
test = false
doc = false

[dependencies]
core = { path = "../libcore" }
libc = { path = "../rustc/libc_shim" }
compiler_builtins = { path = "../rustc/compiler_builtins_shim" }

[build-dependencies]
build_helper = { path = "../build_helper" }
cc = "1.0.1"

[features]
debug = []
