language: rust

rust:
  - stable
  - beta
  - nightly
  - 1.17.0

cache: cargo

script:
  - cargo build --verbose --features "$FEATURES"
  - cargo test --verbose --features "$FEATURES"

env:
  - FEATURES="term_size"
  - FEATURES="hyphenation"

matrix:
  allow_failures:
    - rust: nightly
