[package]
authors = ["The Rust Project Developers"]
name = "rustc_errors"
version = "0.0.0"

[lib]
name = "rustc_errors"
path = "lib.rs"
crate-type = ["dylib"]

[dependencies]
serialize = { path = "../libserialize" }
syntax_pos = { path = "../libsyntax_pos" }
rustc_data_structures = { path = "../librustc_data_structures" }
unicode-width = "0.1.4"
atty = "0.2"
termcolor = "0.3"
