[package]
authors = ["The Rust Project Developers"]
name = "rustc_errors"
version = "0.0.0"

[lib]
name = "rustc_errors"
path = "lib.rs"
crate-type = ["dylib"]

[dependencies]
log = "0.4"
serialize = { path = "../libserialize" }
syntax_pos = { path = "../libsyntax_pos" }
rustc_data_structures = { path = "../librustc_data_structures" }
rustc_cratesio_shim = { path = "../librustc_cratesio_shim" }
unicode-width = "0.1.4"
atty = "0.2"
termcolor = "1.0"
