language: rust
rust:
  - nightly
sudo: false
cache: cargo

matrix:
  include:
    - name: cargo test
      os: osx

    - name: cargo test
      os: linux

    - name: cargo clippy
      rust: nightly
      script:
        - if rustup component add clippy-preview;
          then
            cargo clippy -- -Dwarnings;
          else
            echo 'Skipping clippy';
          fi

    - name: cargo doc
      rust: nightly
      script:
        - RUSTDOCFLAGS=-Dwarnings cargo doc

script:
  - cargo build
  - cargo test
  - cargo test --release

notifications:
  email:
    on_success: never
