[package]
authors = ["The Rust Project Developers"]
name = "rustc-main"
version = "0.0.0"

[[bin]]
name = "rustc_binary"
path = "rustc.rs"

[dependencies]
rustc_target = { path = "../librustc_target" }
rustc_driver = { path = "../librustc_driver" }

[features]
jemalloc = ["rustc_target/jemalloc"]
