language: rust
matrix:
  include:
    # This version is tested to avoid unintentional bumping of the minimum supported Rust version
    - rust: 1.20.0
    - rust: stable
    - os: osx
    - rust: beta
    - rust: nightly
      env: EXTRA_ARGS="--features unstable"

sudo: false
script:
  - cargo test
  - (cd ./test_suite && cargo test $EXTRA_ARGS)

notifications:
  email:
    on_success: never
