[package]
authors = ["The Rust Project Developers"]
name = "rustc_incremental"
version = "0.0.0"

[lib]
name = "rustc_incremental"
path = "lib.rs"
crate-type = ["dylib"]

[dependencies]
graphviz = { path = "../libgraphviz" }
log = "0.4"
rand = "0.4"
rustc = { path = "../librustc" }
rustc_data_structures = { path = "../librustc_data_structures" }
serialize = { path = "../libserialize" }
syntax = { path = "../libsyntax" }
syntax_pos = { path = "../libsyntax_pos" }
