[package]
authors = ["The Rust Project Developers"]
name = "rustbook"
version = "0.1.0"
license = "MIT/Apache-2.0"

[dependencies]
clap = "2.25.0"

[dependencies.mdbook]
version = "0.1.7"
default-features = false
features = ["search"]
